#!/bin/bash
BLUE='\033[0;34m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

if [ -z "$1" ]; then
    read -p "What is project name (without ir.pouyasoft)?  " project
else
    project=$1
fi

if [ -z "$2" ]; then
    read -p "What is database name?  " dbName
else
    dbName=$2
fi

printf "${GREEN}Project: ${BLUE}$project -- ${GREEN}Database: ${BLUE}$dbName\n${NC}"
printf "${GREEN}Command: ${PURPLE}pullDB $project $dbName\n${NC}"

adb shell "su -c 'rm /sdcard/$dbName.sqlite; cat /data/data/$project/databases/$dbName > /sdcard/$dbName.sqlite'"
adb pull /sdcard/$dbName.sqlite ~/File/$dbName.sqlite
nohup /usr/bin/sqliteman ~/File/$dbName.sqlite > /dev/null &

